server:
  port: 22378
config:
  localstack:
    accessKey: dummy
    secretKey: dummy
    region: us-east-1
    sqs:
      scheme: http
      url: localhost:4566
client:
  localstack:
    baseUrl: http://127.0.0.1:4566
